# https://github.com/P3TERX/ActionsVM

name: macOS (tmate)

on:
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        build_type: [Release]
        qt_ver: [6.0.0]
        qt_arch: [clang_64]
    env:
      targetName: lemon
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Run Start Script
      run: source macos-start.sh
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_ver }}
      
    - name: Start SSH via tmate
      uses: P3TERX/ssh2actions@main

    - name: Run End Script
      run: source macos-end.sh
